#
# @file __init__.py
#

import myutils.TurningPoints
import myutils.DirectionalChange
import myutils.PerceptuallyImportant


FindingTurningPoints = TurningPoints.FindingTurningPoints
FindingDirectionalChangePoints = DirectionalChange.FindingDirectionalChangePoints
FindingPerceptuallyImportantPoints = PerceptuallyImportant.FindingPerceptuallyImportantPoints